package com.demo.upimesh.service;

public enum IngestionStatus {
    SETTLED,
    DUPLICATE_DROPPED,
    TAMPERED_REJECTED,
    STALE_REJECTED,
    INVALID_PIN_REJECTED,
    INSUFFICIENT_FUNDS_REJECTED,
    UNKNOWN_ACCOUNT_REJECTED,
    INVALID_PAYMENT_REJECTED,
    ERROR_REJECTED
}
